steps:
# 1. Use the official Docker builder to execute the build command
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'us-central1-docker.pkg.dev/${PROJECT_ID}/sams-repo/sams-backend:latest', # <<-- USE ${PROJECT_ID}
    '.'
  ]

# 2. Configure the options to resolve the log issue
options:
  logging: CLOUD_LOGGING_ONLY